# Generated by Django 4.2.1 on 2023-05-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamz', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imagen',
            field=models.ImageField(upload_to='videos/'),
        ),
    ]
