# Generated by Django 4.2.1 on 2023-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamz', '0005_remove_video_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
