# Generated by Django 4.2.1 on 2023-05-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamz', '0006_alter_video_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='id_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamz.video'),
        ),
    ]
